model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        encoder:
          - class_path: rslearn.models.clip.CLIP
            init_args:
              model_name: "openai/clip-vit-large-patch14-336"
        decoders:
          class:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 1024
                out_channels: 2
                num_fc_layers: 1
            - class_path: rslearn.train.tasks.classification.ClassificationHead
    lr: 0.00002
    plateau: true
    plateau_factor: 0.5
    plateau_patience: 2
    plateau_min_lr: 1e-6
    plateau_cooldown: 10
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    path: weka://dfive-default/rslearn-eai/datasets/minderoo/classifier/dataset_20241002/
    inputs:
      image:
        data_type: "raster"
        layers: ["maxar"]
        bands: ["R", "G", "B"]
        passthrough: true
      label:
        data_type: "vector"
        layers: ["label"]
        is_target: true
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          class:
            class_path: rslearn.train.tasks.classification.ClassificationTask
            init_args:
              property_name: "label"
              classes: ["positive", "negative"]
              prob_property: "prob"
        input_mapping:
          class:
            label: "targets"
    batch_size: 8
    num_workers: 16
    train_config:
      transforms:
        - class_path: rslearn.train.transforms.flip.Flip
      tags:
        split: train
      sampler:
        class_path: rslearn.train.dataset.WeightedRandomSamplerFactory
        init_args:
          option_key: "weight"
          num_samples: 8192
    val_config:
      tags:
        split: val
    test_config:
      tags:
        split: val
trainer:
  max_epochs: 50
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        save_last: true
        monitor: val_class/accuracy
        mode: max
    - class_path: rslearn.train.callbacks.freeze_unfreeze.FreezeUnfreeze
      init_args:
        module_selector: ["model", "encoder", 0]
rslp_project: molmo_comparison
rslp_experiment: minderoo_classify_02_clip_frozen
