model:
  class_path: rslearn.train.lightning_module.RslearnLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        encoder:
          - class_path: rslearn.models.swin.Swin
            init_args:
              input_channels: 7
              output_layers: [1, 3, 5, 7]
              pretrained: true
        decoders:
          class:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 1024
                out_channels: 2
            - class_path: rslearn.train.tasks.classification.ClassificationHead
    lr: 0.0001
    plateau_factor: 0.1
    plateau_patience: 10
    plateau_min_lr: 0
    plateau_cooldown: 0
    restore_config:
      restore_path: gcs://rslearn-eai/datasets/landsat_vessel_detection/artifacts/2024-03-13-landsat-vessels/vessel02_satlas_freeze_crop512_nosatlas_b8first2/best.pth
      remap_prefixes:
        - ["backbone.backbone.", "encoder.0.model."]
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    path: gcs://rslearn-eai/datasets/landsat_vessel_detection/classifier/dataset_20240905/
    inputs:
      image:
        data_type: "raster"
        layers: ["landsat"]
        bands: ["B8", "B2", "B3", "B4", "B5", "B6", "B7"]
        passthrough: true
      label:
        data_type: "vector"
        layers: ["label"]
        is_target: true
    task:
      class_path: rslearn.train.tasks.multi_task.MultiTask
      init_args:
        tasks:
          class:
            class_path: rslearn.train.tasks.classification.ClassificationTask
            init_args:
              property_name: "label"
              classes: ["correct", "incorrect"]
              allow_invalid: true
              skip_unknown_categories: true
              prob_property: "prob"
        input_mapping:
          class:
            label: "targets"
    batch_size: 32
    num_workers: 32
    default_config:
      transforms:
        - class_path: rslearn.train.transforms.normalize.Normalize
          init_args:
            mean: 0
            std: 255
        - class_path: rslearn.train.transforms.pad.Pad
          init_args:
            mode: "center"
            size: 32
        - class_path: rslearn.train.transforms.flip.Flip
      groups: ["selected_copy", "phase2a_completed"]
    train_config:
      tags:
        split: train
      sampler:
        class_path: rslearn.train.dataset.WeightedRandomSamplerFactory
        init_args:
          option_key: "weight"
          num_samples: 1000
    val_config:
      groups: ["phase2a_completed"]
      tags:
        split: val
    test_config:
      groups: ["phase2a_completed"]
      tags:
        split: val
    predict_config:
      groups: ["phase2a_completed"]
      tags:
        split: val
trainer:
  max_epochs: 64
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: rslearn.train.prediction_writer.RslearnWriter
      init_args:
        path: gcs://rslearn-eai/datasets/landsat_vessel_detection/classifier/dataset_20240905/
        output_layer: output
        selector: ["class"]
#  limit_train_batches: 64
rslp_project: rslearn-landsat-recheck
rslp_experiment: phase12_20240919_01_copy
