model:
  class_path: MyLightningModule
  init_args:
    model:
      class_path: rslearn.models.multitask.MultiTaskModel
      init_args:
        encoder:
          - class_path: rslearn.models.satlaspretrain.SatlasPretrain
            init_args:
              model_identifier: "Sentinel2_SwinB_SI_RGB"
              fpn: true
        decoders:
          length:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 128
                out_channels: 1
                num_conv_layers: 1
                num_fc_layers: 2
            - class_path: rslearn.train.tasks.regression.RegressionHead
          width:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 128
                out_channels: 1
                num_conv_layers: 1
                num_fc_layers: 2
            - class_path: rslearn.train.tasks.regression.RegressionHead
          speed:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 128
                out_channels: 1
                num_conv_layers: 1
                num_fc_layers: 2
            - class_path: rslearn.train.tasks.regression.RegressionHead
          heading_x:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 128
                out_channels: 1
                num_conv_layers: 1
                num_fc_layers: 2
            - class_path: rslearn.train.tasks.regression.RegressionHead
          heading_y:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 128
                out_channels: 1
                num_conv_layers: 1
                num_fc_layers: 2
            - class_path: rslearn.train.tasks.regression.RegressionHead
          ship_type:
            - class_path: rslearn.models.pooling_decoder.PoolingDecoder
              init_args:
                in_channels: 128
                out_channels: 8
                num_conv_layers: 1
                num_fc_layers: 2
            - class_path: rslearn.train.tasks.classification.ClassificationHead
    lr: 0.0001
    plateau_factor: 0.1
    plateau_patience: 10
    plateau_min_lr: 0
    plateau_cooldown: 0
data:
  class_path: rslearn.train.data_module.RslearnDataModule
  init_args:
    root_dir: "/data/favyenb/rslearn_sentinel2_vessel_postprocess/"
    inputs:
      image:
        data_type: "raster"
        layers: ["sentinel2"]
        bands: ["B04", "B03", "B02"]
        passthrough: true
      info:
        data_type: "vector"
        layers: ["info"]
    task:
      class_path: MyMultiTask
      init_args:
        tasks:
          length:
            class_path: rslearn.train.tasks.regression.RegressionTask
            init_args:
              property_name: "length"
              allow_invalid: true
              scale_factor: 0.01
              metric_mode: l1
          width:
            class_path: rslearn.train.tasks.regression.RegressionTask
            init_args:
              property_name: "width"
              allow_invalid: true
              scale_factor: 0.01
              metric_mode: l1
          speed:
            class_path: rslearn.train.tasks.regression.RegressionTask
            init_args:
              property_name: "sog"
              allow_invalid: true
              scale_factor: 0.01
              metric_mode: l1
          heading_x:
            class_path: rslearn.train.tasks.regression.RegressionTask
            init_args:
              property_name: "cog_x"
              allow_invalid: true
              metric_mode: l1
          heading_y:
            class_path: rslearn.train.tasks.regression.RegressionTask
            init_args:
              property_name: "cog_y"
              allow_invalid: true
              metric_mode: l1
          ship_type:
            class_path: rslearn.train.tasks.classification.ClassificationTask
            init_args:
              property_name: "type"
              allow_invalid: true
              classes: ["cargo", "tanker", "passenger", "service", "pleasure", "fishing", "enforcement", "sar"]
        input_mapping:
          length:
            info: "targets"
          width:
            info: "targets"
          speed:
            info: "targets"
          heading_x:
            info: "targets"
          heading_y:
            info: "targets"
          ship_type:
            info: "targets"
    batch_size: 32
    num_workers: 32
    default_config:
      transforms:
        - class_path: rslearn.train.transforms.normalize.Normalize
          init_args:
            mean: 50
            std: 80
            valid_range: [0, 1]
    train_config:
      groups: ["detections"]
    val_config:
      groups: ["detections_val"]
    test_config:
      groups: ["detections_val"]
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: rslearn-sentinel2-vessel-attribute
      log_model: "all"
      name: rgb_noflip_satlaspretrain_fpn
  max_epochs: 50
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
#  limit_train_batches: 64
